function graphics_ = gXbias_graphics(varargin)

x = 0;
y = 5;
arg_dXdots = { ...
    'x',            x, ...
    'y',            y, ...
    'density',      40, ...
    'diameter',     7, ...
    'size',         3, ...
    'speed',        4, ...
    'coherence',    100, ...
    'direction',    0, ...
    'dirDomain',    [], ...
    'dirCDF',       [], ...
    'userData',     5, ...
    'color',        [1,1,1]*255};

arg_dXtarget = { ...
    'x',            0, ...
    'y',            0, ...
    'penWidth',     1, ...
    'diameter',     {.4, .2}, ...
    'diameter2',	{6, 4}, ...
    'color',        {[1,0,0,1]*255, [0,1,0,1]*255}};

arg_dXline = { ...
    'x1',           x, ...
    'y1',           y, ...
    'x2',           1, ...
    'y2',           1, ...
    'penWidth',     3, ...
    'color',        [1,0,1,1]*255};

arg_dXtext = { ...
    'x',            {1 2}, ...
    'y',            {1 2}, ...
    'size',         30, ...
    'string',       {'R', 'L'}, ...
    'color',        [1,0,1,1]*255};

% {'group', reuse, set now, set always}
reswap = {'current', false, true, false};
graphics_ = { ...
    'dXline',       2,  reswap, arg_dXline; ...
    'dXtext',       2,  reswap, arg_dXtext; ...
    'dXdots',       1,  reswap, arg_dXdots; ...
    'dXtarget',     2,  reswap, arg_dXtarget; ...
    };