% % this is from psychtoolbox 
% mex -v -outdir ../Projects/MacOSX/build -output PsychHID ...
%     -largeArrayDims -DPTBMODULE_PsychHID LDFLAGS="\$LDFLAGS ...
%     -framework ApplicationServices -framework CoreServices -framework ...
%     CoreFoundation -framework Carbon -framework CoreAudio ...
%     -framework IOKit" -I/usr/include -ICommon/Base -IOSX/Base ...
%     -ICommon/PsychHID -IOSX/PsychHID -I../Cohorts/HID_Utilities_64Bit/ ...
%     -I../Cohorts/HID_Utilities_64Bit/IOHIDManager  "Common/PsychHID/*.c" ...
%     "OSX/PsychHID/*.c" "OSX/Base/*.c" "Common/Base/*.c" ...
%     ../Cohorts/HID_Utilities_64Bit/build/Release/libHID_Utilities64.a

% this is what I used
% 10/20/16 added line for UINT16_T to compile on Yosemite
%   see: http://stackoverflow.com/questions/22367516/mex-compile-error-unknown-type-name-char16-t
   mex -v -Dchar16_t=UINT16_T -output mexHID ...
    -largeArrayDims LDFLAGS="\$LDFLAGS ...
    -framework ApplicationServices -framework CoreServices -framework ...
    CoreFoundation -framework Carbon -framework CoreAudio ...
    -framework IOKit" -I/usr/include mexHID.c mexHID-OSX.c


