function index_ = taskCohTimeLearn_interleaved_cohQuest(varargin)
%Do a training coherence Quest for the interleaved cohTimeLearn task
%
%   index_ = taskCohTimeLearn_interleaved_cohQuest(varargin)
%
%   optional eye tracker for fixation
%   lpHID choices
%
%   index_ specifies the new instance in ROOT_STRUCT.dXtask

% copyright 2008 Benjamin Heasly University of Pennsylvania

% name for this task
name = mfilename;

if nargin >= 2

    % ASL and sound info
    settings = varargin{1};

    % number of trials
    numTrials = varargin{2};

    varargin(1:2) = [];
else
    warning(sprintf('%s using default values', mfilename));
    settings.useASL = true;
    settings.mouseMode = false;
    settings.mute = false;
    settings.dotDir = [0 180];
    settings.viewingTimes = [100 200 400 800];
    numTrials = 10;
end

% number of trials and nuber of dXtc conditons
%   give the number of blocks
nVT = length(settings.viewingTimes);
numBlocks = ceil(numTrials/length(settings.dotDir)/nVT);

% a name for each viewing time
for ii = 1:nVT
    qNames{ii} = sprintf('cohQ81_%dms\n', settings.viewingTimes(ii));
end

% dXquest to asses 81% correct coherence at each viewing time
arg_dXquest = { ...
    'stimRange',    [.5, 200], ...
    'stimValues',   1:100, ...
    'refStim',      1, ...
    'blankStim',	[], ...
    'guessStim',    50, ...
    'Tstd',         9, ...
    'estimateType', 'mean', ...
    'psychParams',  [0 2.5 .01 .5], ...
    'goPastConvergence', true, ...
    'name',         qNames,...
    'ptr',          {{'dXdots', 1, 'coherence'}}, ...
    'showPlot',     false, ...
    'doEndTrial',   false};

% dXtc for viewing time condition and dot direction
arg_dXtc = { ...
    'name',     {'dot_dir', 'viewing_time'}, ...
    'values',	{settings.dotDir, settings.viewingTimes}, ...
    'ptr',      {{'dXdots', 1, 'direction'}, {}}};

arg_dXlr = { ...
    'ptr',      {{'dXdots', 1, 'direction'}}};

% args to make statelist polymorphic
ptrs = {'dXtc', 'dXlr'};
vtcon = {'wait', {'dXtc', 2, 'value'}, []};
PQ = @cohTimeLearn_pickQuestCondition;
arg_statelist = {ptrs, vtcon, PQ, settings};

% {'group', reuse, set now, set always}
reswap = {'current', false, true, false};
ta = cohTimeLearn_task_args;
index_ = rAdd('dXtask', 1, {'root', false, true, false}, ...
    'name',         name(5:end), ...
    'blockReps',    numBlocks, ...
    'userData',     settings.viewingTimes, ...
    'endTaskFcn',   {@cohTimeLearn_interleaved_saveCohThresh}, ...
    'helpers', ...
    { ...
    'dXquest',                  nVT,reswap, arg_dXquest; ...
    'dXtc',                     2,  reswap, arg_dXtc; ...
    'dXlr',                     1,  reswap, arg_dXlr; ...
    'gXcohTimeLearn_hardware',	1,  true,   {settings}; ...
    'gXcohTimeLearn_graphics',	1,  true,	{settings}; ...
    'gXcohTimeLearn_statelist',	1,  false,	arg_statelist; ...
    }, ...
    ta{:}, varargin{:});