rInit('remote')

arg_dXdots = { ...
    'x',            {-7 7 -7 7}, ...
    'y',            {5 5 -5 -5}, ...
    'diameter',     8, ...
    'size',         3, ...
    'speed',        5, ...
    'coherence',    {51.2 51.2 10 10}, ...
    'direction',    85, ...
    'density',      {50 16.7 50 16.7}, ...
    'wrapMode',     'wrap', ...
    'color',        [1 1 1 1]*255, ...
    'bgColor',      [0 0 0]};

rAdd('dXdots', 4, arg_dXdots{:})

rGraphicsShow;
rGraphicsDraw(inf)

rDone