H_2_file_names = ...
    {...
%     'Justin_44_main_18.mat'...
%       'Justin_44_main_20.mat'...
%       'Justin_44_main_22.mat'...
%       'Justin_44_main_24.mat'...
%      'Justin_44_main_26.mat', ...
%      'Justin_44_main_28.mat', ...
       'Justin_44_main_31.mat'...
      'Justin_44_main_33.mat', ...
};

H_tenth_filenames = ...
    {...
%     'Justin_44_main_17.mat'...
%       'Justin_44_main_19.mat', ...
%       'Justin_44_main_21.mat', ...
%       'Justin_44_main_23.mat'...
%      'Justin_44_main_25.mat', ...
%      'Justin_44_main_27.mat', ...
       'Justin_44_main_30.mat'...
      'Justin_44_main_32.mat', ...

    };

% data_cleanser(H_2_file_names, '2','low')
% data_cleanser(H_tenth_filenames,'tenth','low')

data_cleanser_1(H_2_file_names, '2','low')
data_cleanser_1(H_tenth_filenames,'tenth','low')

%data plotter 1 now works
