function topNode =  DBSconfigure(varargin)
%% function topNode =  DBSconfigure(varargin)
%
% This function sets up a DBS experiment. We keep this logic separate from
% running and cleaning up an experiment because we may want to decide
% when/how do do those other things on the fly (e.g., add/subtract tasks
% depending on the subject's motivation, etc).
%
% Arguments:
%  varargin  ... optional <property>, <value> pairs for settings variables
%                 note that <property> can be a cell array for nested
%                 property structures in the task object
%
% Returns:
%  mainTreeNode ... the topsTreeNode at the top of the hierarchy
%
% 11/17/18   jig wrote it

%% ---- Parse arguments for configuration settings
%
% Name of the experiment, which determines where data are are stored
name = 'DBSStudy';

% Other defaults
settings = { ...
   'taskSpecs',                  {'VGS' 1 'NN' 1 'Quest' 1 'AN' 1 'SN' 1 'NL' 1 'NR' 1}, ...
   'runGUIname',                 'eyeGUI', ...
   'databaseGUIname',            [], ...
   'remoteDrawing',              true, ...
   'instructionDuration',        1.0, ...
   'displayIndex',               1, ... % 0=small, 1=main
   'uiList',                     'dotsReadableEyePupilLabs', ...
   'doCalibration',              true, ...
   'doRecording',                true, ...
   'queryDuringCalibration',     false, ...
   'sendTTLs',                   false, ...
   'targetDistance',             10, ...
   'gazeWindowSize',             6, ...
   'gazeWindowDuration',         0.15, ...
   'saccadeDirections',          0:90:270, ...
   'dotDirections',              [0 180], ...
   'referenceRT',                500, ... % for speed feedback   
   'smiley',                     {'smiley.jpg'}, ... % feedback
   'goodJob',                    {'GoodJob.jpg'}, ...
   'playables',                  {'correct.mp3', 'error.wav'};
   };

% Update from argument list (property/value pairs)
for ii = 1:2:nargin
   settings{find(strcmp(varargin{ii}, settings),1) + 1} = varargin{ii+1};
end

%% ---- Create topsTreeNodeTopNode to control the experiment
%
% Make the topsTreeNodeTopNode
topNode = topsTreeNodeTopNode(name);

% Add a topsGroupedList as the nodeData, plus other fields, then configure
topNode.nodeData = topsGroupedList.createGroupFromList('Settings', settings);

% Add GUIS
topNode.addGUIs('run', topNode.nodeData{'Settings'}{'runGUIname'}, ...
   'database', topNode.nodeData{'Settings'}{'databaseGUIname'});

% Add the screen and feedback drawable ensemble
topNode.addSharedDrawables( ...
   topNode.nodeData{'Settings'}{'displayIndex'}, ...
   topNode.nodeData{'Settings'}{'remoteDrawing'}, ...
   {'dotsDrawableText', 'dotsDrawableText', 'dotsDrawableImages', 'dotsDrawableImages'}, ...
   {{'isVisible', false}, {'isVisible', false}, ...
   {'isVisible', false, 'height', 2, 'fileNames', topNode.nodeData{'Settings'}{'smiley'}}, ...
   {'isVisible', false, 'height', 10, 'fileNames', topNode.nodeData{'Settings'}{'goodJob'}}}, ...
   true, true);
         
% Add the user interface device(s) with default settings
topNode.addSharedReadables(topNode.nodeData{'Settings'}{'uiList'}, [], ...
   topNode.nodeData{'Settings'}{'doCalibration'}, ...
   topNode.nodeData{'Settings'}{'doRecording'});

% Add playables (feedback sounds)
topNode.addSharedPlayables( ...
   topNode.nodeData{'Settings'}{'playables'}, ...
   {'isBlocking', false});

%% ---- Make call lists to show text/images between tasks
%
%  Use the sharedHelper drwawableEnsemble
%
% Welcome call list
welcome = topsCallList();
welcome.alwaysRunning = false;
paceStr = 'Work at your own pace.';
strs = { ...
   'dotsReadableEye',         paceStr, 'Each trial starts by fixating the central cross.'; ...
   'dotsReadableHIDButtons',  paceStr, 'Each trial starts by pusing either button.'; ...
   'dotsReadableHIDKeyboard', paceStr, 'Each trial starts by pressing the space bar.'; ...
   'dotsReadableDummy',       '',      'Each trial starts automatically.'; ...
   'default',                 '',      'You are on your own.'};
strind = size(strs,1);
if ~isempty(topNode.sharedHelpers.readables)
    strind = find(cellfun(@(x) isa(topNode.sharedHelpers.readables{1}, x), strs(1:end-1,1)));
end    
welcome.addCall({@dotsDrawableText.drawEnsemble, ...
   topNode.sharedHelpers.drawables, strs(strind, 2:3), true, 2}, 'Welcome');

% Countdown call list
countdown = topsCallList();
countdown.alwaysRunning = false;
countdown.addCall({@dotsDrawable.drawEnsemble, ...
      topNode.sharedHelpers.drawables, { ...
      {'isVisible', true, 'y', -9}, ...
      {'isVisible', false,}, ...
      {'isVisible', false}, ...
      {'isVisible', true, 'y', 1, 'height', 13, ...
      'width', [], 'fileNames', topNode.nodeData{'Settings'}{'goodJob'}}}, ...
      true}, 'set');
for ii = 1:10
   countdown.addCall({@dotsDrawable.drawEnsemble, ...
      topNode.sharedHelpers.drawables, { ...
      {'string', sprintf('Next task starts in: %d', 10-ii+1)}}, ...
      false, 1, 0}, sprintf('text%d', ii));
end
   
%% ---- Loop through the task specs array, making tasks with appropriate arg lists
%
taskSpecs = topNode.nodeData{'Settings'}{'taskSpecs'};
QuestTask = [];
noDots    = true;
for ii = 1:2:length(taskSpecs)
   
   % Make list of properties to send
   args = { ...
      {'settings',  'targetDistance'},       topNode.nodeData{'Settings'}{'targetDistance'}, ...
      {'settings',  'gazeWindowSize'},       topNode.nodeData{'Settings'}{'gazeWindowSize'}, ...
      {'settings',  'gazeWindowDuration'}, 	topNode.nodeData{'Settings'}{'gazeWindowDuration'}, ...
      {'timing',    'showInstructions_shi'},	topNode.nodeData{'Settings'}{'instructionDuration'}, ...
      'sendTTLs',                            topNode.nodeData{'Settings'}{'sendTTLs'}, ...
      'taskID',                              (ii+1)/2, ...
      'taskTypeID',  find(strcmp(taskSpecs{ii}, {'VGS' 'MGS' 'Quest' 'NN' 'NL' 'NR' 'SN' 'SL' 'SR' 'AN' 'AL' 'AR'}),1)};
   
   switch taskSpecs{ii}
      
      case {'VGS' 'MGS'}
         
         % Make Saccade task with args
         task = topsTreeNodeTaskSaccade.getStandardConfiguration( ...
            taskSpecs{ii}, taskSpecs{ii+1}, ...
            {'direction', {'values', topNode.nodeData{'Settings'}{'saccadeDirections'}}}, ...
            args{:});
         
      otherwise
         
         % If there was a Quest task, use to update coherences in other tasks
         if ~isempty(QuestTask)
            args = cat(2, args, ...
               {{'settings' 'useQuest'},   QuestTask, ...
               {'settings' 'referenceRT'}, QuestTask});
         end
         
         % Make RTDots task with args
         task = topsTreeNodeTaskRTDots.getStandardConfiguration( ...
            taskSpecs{ii}, taskSpecs{ii+1}, ...
            {'direction', {'values', topNode.nodeData{'Settings'}{'dotDirections'}}}, ...
            args{:});
         
         % Add special instructions for first dots task
         if noDots
            task.settings.textStrings = cat(1, ...
               {'When flickering dots appear, decide their overall direction', ...
               'of motion, then look at the target in that direction'}, ...
               task.settings.textStrings);
            noDots = false;
         end
         
         % Special case of quest ... use output as coh/RT refs
         if strcmp(taskSpecs{ii}, 'Quest')
            QuestTask = task;
         end
   end
   
   % Add some fevalables to show instructions/feedback before/after tasks
   if ii == 1
      task.startFevalable = {@run, welcome};
   else
      task.startFevalable = {@run, countdown};
   end
   
   % Add as child to the maintask.
   topNode.addChild(task);
end
