function topNode = DBSrun(location, varargin)
%% function [mainTreeNode, datatub] = DBSrun(location, varargin)
%
% DBSrun = Response-Time Dots
%
% This function configures, initializes, runs, and cleans up a DBS 
%  experiment (OR or office)
%
% Arguments:
%  location    ... string name, listed below
%  varargin    ... property/value pairs, as in arglists below
%
% 11/17/18   jig wrote it

%% ---- Clear globals
%
% umm, duh
clear globals

%% ---- Configure experiment based on location
%
% UIs:
%  'dotsReadableEyeEyelink'
%  'dotsReadableEyePupilLabs'
%  'dotsReadableEyeEOG'
%  'dotsReadableHIDKeyboard'
%  'dotsReadableEyeMouseSimulator'
%  'dotsReadableHIDButtons'
%  'dotsReadableHIDGamepad'

if nargin < 1 || isempty(location)
   location = 'OR';
end

switch location
   
   case {'calibrate' 'Calibrate'}
      arglist = { ...
         'taskSpecs',            {'VGS' 1}, ...
         'readables',            {'dotsReadableEyePupilLabs'}, ...
         'displayIndex',         0, ... % 0=small, 1=main
         'remoteDrawing',        false, ...
         'sendTTLs',             false, ...
         'showEye',              true, ...
         };
      
   case {'or' 'OR'}
      arglist = { ...
         'taskSpecs',            {'VGS' 5 'MGS' 5 'Quest' 40 'SN' 40 'AN' 40}, ...
         'readables',            {'dotsReadableEyeEOG'}, ... 
         'sendTTLs',             true, ...
         };
      
   case {'orh' 'ORH'}
      arglist = { ...
         'taskSpecs',            {'VGS' 5 'MGS' 5 'Quest' 40 'SN' 40 'AN' 40}, ...
         'readables',            {'dotsReadableEyeEOG'}, ...
         'saccadeDirections',    [0 180], ...
         'sendTTLs',             true, ...
         };
     
   case {'orSaccades' 'ORSACCADES'}
      arglist = { ...
         'taskSpecs',            {'VGS' 5 'MGS' 5 'VGS' 5 'MGS' 5 'VGS' 5 'MGS' 5}, ...
         'readables',            {'dotsReadableEyeEOG'}, ...
         'sendTTLs',             true, ...
         };
            
   case {'buttons' 'Buttons'}  % Or using buttons
      arglist = { ...
         'taskSpecs',            {'Quest' 40 'SN' 40 'AN' 40}, ...
         'sendTTLs',             true, ...
         'readables',            {'dotsReadableHIDButtons'}, ... 
         };
   
   case {'debug' 'Debug'}
      arglist = { ...
         'taskSpecs',            {'VGS' 10 'Quest' 4 'SN' 1 'AN' 1}, ...%{'Quest' 50 'SN' 50 'AN' 50}, ...
         'readables',            {'dotsReadableHIDKeyboard'}, ... 
         'displayIndex',         0, ... % 0=small, 1=main
         'remoteDrawing',        false, ...
         'sendTTLs',             true, ...
         };
      
   otherwise % office
      arglist = { ...
         'taskSpecs',            {'VGS' 5 'MGS' 5 'Quest' 40 'SN' 25 'AN' 25}, ...
         'readables',            {'dotsReadableEyePupilLabs'}, ... 
         'remoteDrawing',        true, ...
         };
end

%% ---- Call the configuration routine
%
topNode = DBSconfigure(arglist{:});

%% ---- Run it!
%
topNode.run();