function arg_dXtask_ = modality_task_args
% return some dXtask argumnets for the fine discrimination task

feedbackSelect = { ...
    'showPctGood',      false; ...
    'showNumGood',      true; ...
    'showGoodRate',     false; ...
    'showPctCorrect',   true; ...
    'showNumCorrect',   true; ...
    'showCorrectRate',  false; ...
    'showTrialCount',   false; ...
    'showMoreFeedback', true};
feedbackSelect = cell2struct(feedbackSelect(:,2), feedbackSelect(:,1), 1);

arg_dXtask_ = { ...
    'statesToFIRA',     { ...
                        'clear',    3; ...
                        'indicate', 3; ...
                        'acquire',  1; ...
                        'hold',     1; ...
                        'settle',   1; ...
                        'tone1',    1; ...
                        'tone2',    1; ...
                        'showInt1', 3; ...
                        'offInt1',  3; ...
                        'showInt2', 3; ...
                        'respond',  3; ...
                        'left',     1; ...
                        'right',    1; ...
                        'correct',  1; ...
                        'incorrect',1; ...
                        'error',	3; ...
                        'end',      3; ...
                        }, ...
    'wrtState',         'showInt1', ...
    'objectsToFIRA',    {'saveToFIRA'}, ...
    'anyStates',        {'correct', 'incorrect'}, ...
    'trialOrder',       'random', ...
    'feedbackSelect',   feedbackSelect, ...
    'endTaskFcn',       {@fineBreak}, ...
    'showFeedback',     true, ...
    'moreFeedbackFunction', @fineEarnings, ...
    'timeout',          3600};