function arg_dXtask_ = modality_task_args
% return the partial list of dXtask argumnets that is common to all
% response modality tasks

feedbackSelect = { ...
    'showPctGood',      false; ...
    'showNumGood',      true; ...
    'showGoodRate',     false; ...
    'showPctCorrect',   true; ...
    'showNumCorrect',   true; ...
    'showCorrectRate',  true; ...
    'showTrialCount',   false; ...
    'showMoreFeedback', false};
feedbackSelect = cell2struct(feedbackSelect(:,2), feedbackSelect(:,1), 1);

arg_dXtask_ = { ...
    'statesToFIRA',     { ...
                        'clear',    3; ...
                        'indicate', 3; ...
                        'acquire',  1; ...
                        'hold',     1; ...
                        'settle',   1; ...
                        'showStim', 3; ...
                        'noStim',   3; ...
                        'choose',   3; ...
                        'left',     3; ...
                        'right',    3; ...
                        'up',       3; ...
                        'down',     3; ...
                        'both',     1; ...
                        'correct',	1; ...
                        'incorrect',1; ...
                        'error',	3; ...
                        'end',      3; ...
                        }, ...
    'wrtState',         'showStim', ...
    'objectsToFIRA',    {'saveToFIRA'}, ...
    'anyStates',        {'correct', 'incorrect'}, ...
    'bgColor',          [0,0,0], ...
    'trialOrder',       'random', ...
    'feedbackSelect',   feedbackSelect, ...
    'showFeedback',     true, ...
    'timeout',          3600};