soundList={     'Pause.wav',...
                '1 up.wav', ...
                'Cannon Shot.wav', ...
                'Fireball.wav', ...
                'Mario Jump.wav', ...
                'Power Up.wav', ...
                'Super Mario 2 - Die.wav', ...
                'Super Mario 2 - Door.wav', ...
                'Super Mario 2 - Jump.wav',...
                'Super Mario 3 - Power Up.wav', ...
                'Super Mario 3 - Start Stage.wav', ...
                'Super Mario 2 - Lose Chance.wav',...
                'Super Mario 2 - Throw.wav', ...
                'Super Mario 2 - Game Over.wav', ...
                'Mario Jump.wav', ...
                'Super Mario 2 - Pick Up.wav',...
                'LOZ_Bomb_Drop.wav', ...
                'LOZ_Get_Item.wav', ...
                'LOZ_Get_Rupee.wav', ...
                'LOZ_Key.wav', ...
                'LOZ_Kill.wav', ...
                'LOZ_MagicalRod.wav', ...
                'AOL_Battle.wav', ...
                'AOL_Deflect.wav', ...
                'AOL_Elevator.wav', ...
                'AOL_Kill.wav', ...
                'AOL_LearnSpell.wav', ...
                'AOL_Map.wav', ...
                'AOL_Menu_Alphabet.wav', ...
                'AOL_Menu_Erase.wav', ...
                'AOL_Spell.wav', ...
                'AOL_Sword_Clang.wav', ...
                'AOL_Sword_Hit.wav', ...
                'AOL_Sword_Shoot.wav', ...
                };