rInit('local');

rAdd('dXdots', 1, 'visible', true, 'direction', 0.00, 'density', 33, ...
    'speed', 3, 'diameter', 6, 'color', 1, ...
    'coherence', 100, ...
    'x', 0, ...
    'y', 0, 'deltaDir', 0, ...
    'lifetimeMode', 'limit', ...
    'flickerMode',  'random', ...
    'wrapMode',     'wrap');

rGraphicsDraw(inf);
rDone;
