function contrast_ = gXnachmias_testContrast

% central fixation, a contrast Gaussian, and an indicator ring around the
% Gaussian

% Roughly reproduce modelfest stimulus #26, a circular gaussian bright
% patch with gaussian onset and offset
%   see http://vision.arc.nasa.gov/modelfest/stimuli.html

% according to modelfest, we want 30cd/m^2 background.
% this is 31.555% of the Johnson 115 Viewsonic's Lmax=97.5cd/m^2,
bgLum = 0.31555;

% According to modelfest data, a Gaussian contrast stimulus has its 82%
% correct threshold at -log10("Contrast") = ~1.2.
%	(see http://vision.arc.nasa.gov/modelfest/data.html)
% So, "Contrast" = .063.
C = .063;

% pick a bright-dark-symmetric range of lower contrasts.
nLum = 6;
CLin = linspace(-C, 0, nLum/2);
CLin = [CLin, -fliplr(CLin)];

% Assuming Lmin = bgLum, What is Lmax?  It depends
% on the form of "Contrast":

% If Webber Fraction, Lmax = (W+1)*Lmin,
%   Webber makes sense because there is a definite, dominatinf background
%   to compare to.  But there are no sharp edges.
Lweb = (CLin+1).*bgLum;

% If Michelson Contrast, Lmax = ((M+1)*Lmin))/(1-M)
%   Michelson also makes sense because the thing is a smooth texture.
%   But there is not a screen-wide spatial frequency texture
%   M. generates larger/easier contrasts than Webber in this case
Lmic = ((CLin+1).*bgLum)./(1-CLin);

% compare Weber to Michelson
% plot(CLin, Lweb, CLin, Lmic);xlabel('contrast'); ylabel('CRT luminance fraction')

% pick Webber contrast
lums = num2cell(Lweb);

stimD = 5;

arg_dXtexture = { ...
    'lum',          lums, ...
    'bgLum',        bgLum, ...
    'privateBackground', false,	...
    'textureStyle', 'monoCircleGauss', ...
    'duration',     200, ...
    'continuous',   false, ...
    'x',            0, ...
    'y',            0, ...
    'w',            stimD, ...
    'sourceRect',   [], ...
    'rotation',     0, ...
    'preload',      true};

arg_dXfunctionCaller = { ...
    'function',     {@rGraphicsShow, @rSet}, ...
    'class',        'dXtexture', ...
    'indices',      {1, []}, ...
    'args',         {{}, {'imageIndex', 1}}, ...
    'doEndTrial',   {false, true}};

% targets 1 and 2 act like a black and white donut.  target 2 penwidth is
% supposed to make equal areas of black and white.
arg_dXtarget = { ...
    'x',            0, ...
    'y',            0, ...
    'penWidth',     {1,1.0722,1}, ...
    'diameter',     {.4, .4, .5+sqrt(2)*stimD}, ...
    'color',        lums([end, 1, end]), ...
    'cmd',          {0,1,1}};

tony = {'current', true, true, false};
contrast_ = { ...
    'dXtexture',	nLum,	tony,	arg_dXtexture; ...
    'dXfunctionCaller', 2,  tony,	arg_dXfunctionCaller; ...
    'dXtarget',     3,      tony,	arg_dXtarget};