function helpers_ = gXnachmias_helpers
% BSH: factor out object arguments common to all of the tasks used to
% measure the psychometric function near its accelerating shoulder.  These
% tasks are the collaborations with Jacob Nachmias.

% disp(['HEY BUTTHEAD, THE BEEPS ARE MUTED (',mfilename,').'])

arg_dXbeep = { ...
    'mute',         false, ...
    'frequency',    {783.99,    1046.5,	493.88, 391.995}, ...
    'duration',     {.100,      .500,	.250,   .300}};

arg_dXfeedback = { ...
    'doEndTrial',       'block', ...
    'size',             22, ...
    'bold',             true, ...
    'x',                -16, ...
    'tasksColor',       [1 1 0]*255, ...
    'totalsColor',      [1 1 0]*255, ...
    'displaySecs',      6e2};

arg_dXlpHID = {};

arg_dXkbHID = {};

tony = {'root', true, true, false};
helpers_ = { ...
    'dXbeep',       4, tony, arg_dXbeep; ...
    'dXfeedback',   1, tony, arg_dXfeedback; ...
    'dXlpHID',      1, tony, arg_dXlpHID; ...
    'dXkbHID',      1, tony, arg_dXkbHID};