function args_task_ = common_task_args
% return the partial list of dXtask argumnets that is common to many tasks

feedbackSelect = { ...
    'showPctGood',      false; ...
    'showNumGood',      false; ...
    'showGoodRate',     false; ...
    'showPctCorrect',   true; ...
    'showNumCorrect',   false; ...
    'showCorrectRate',  false; ...
    'showTrialCount',   false; ...
    'showMoreFeedback', false};
feedbackSelect = cell2struct(feedbackSelect(:,2), feedbackSelect(:,1), 1);

args_task_ = { ...
    'statesToFIRA', {'indicate', 3; 'hideFP', 3; 'showStim', 3; ...
    'hideStim', 3; 'left', 1; 'right', 1; 'both', 1; ...
    'correct', 1; 'incorrect', 1; 'abstain', 1; 'error', 1}, ...
    'objectsToFIRA', {'saveToFIRA'}, ...
    'anyStates',	{'correct', 'incorrect', 'abstain'}, ...
    'wrtState',     'showStim', ...
    'trialOrder',   'random', ...
    'feedbackSelect',feedbackSelect, ...
    'showFeedback', true};