function dots_ = gXnachmias_dots

% central fixation, a dots field, and an indicator ring around the dots

stimD = 5;

arg_dXdots = { ...
    'x',            0, ...
    'y',            0, ...
    'diameter',     stimD, ...
    'size',         3, ...
    'speed',        5, ...
    'coherence',    0, ...
    'direction',    0, ...
    'density',      16.7, ...
    'color',        [1,1,1]*255};

arg_dXfunctionCaller = { ...
    'function',     @rGraphicsShow, ...
    'class',        'dXdots', ...
    'indices',      1};

arg_dXtarget = { ...
    'x',            0, ...
    'y',            0, ...
    'penWidth',     1, ...
    'diameter',     {.4, .5+sqrt(2)*stimD}, ...
    'color',        {.5, .125}, ...
    'cmd',          {0,1}};

tony = {'current', true, true, false};
dots_ = { ...
    'dXtarget',     2,      tony,   arg_dXtarget; ...
    'dXdots',       1,      tony,   arg_dXdots; ...
    'dXfunctionCaller', 1,  tony,   arg_dXfunctionCaller};