function index_ = taskDetectLDots(varargin)
%Dots task for leftward motion detection, near accelerating PF shoulder
%   index_ = taskDetectLDots(varargin)
%
%   no eyetracker
%   lpHID choices
%
%   varargin gets passed to dXtask/set via rAdd.
%
%   index_ specifies the new instance in ROOT_STRUCT.dXtask

% Copyright 2006 by Benjamin Heasly
%   University of Pennsylvania

arg_dXtc = { ...
    'name',         {'dot_coh', 'dot_dir'}, ...
    'values',       {[0 0 0 0 0 1.6 3.2 6.4 12.8 25.6], [180]}, ...
    'ptr',          {{'dXdots', 1, 'coherence'}, {'dXdots', 1, 'direction'}}};

arg_dXblank = { ...
    'ptr',          {{'dXdots', 1, 'coherence'}}};

% statelist options that make this task special
lcon = {'jump', {'dXblank', 1, 'value'}, [0 1], {'incorrect'; 'correct'}};
rcon = {'jump', {'dXblank', 1, 'value'}, [0 1], {'error'; 'error'}};
bcon = {'jump', {'dXblank', 1, 'value'}, [0 1], {'correct'; 'incorrect'}};
ptrs = {'dXtc', 'dXblank'};
nofp = {{}, 'dXtarget', 1};
show = 200;
arg_statelist = {lcon, rcon, bcon, ptrs, nofp, show};

name = mfilename;
cta = common_task_args;
index_ = rAdd('dXtask', 1, {'root', false, true, false}, ...
    'name',	name(5:end), ...
    'blockReps', 12, ...
    'bgColor', [0,0,0], ...
    'helpers', { ...
    'dXtc',             2,	{'current', false, true, false},	arg_dXtc; ...
    'dXblank',          1,	{'current', false, true, true},     arg_dXblank; ...
    'gXnachmias_dots',  1,  true,                               []; ...
    'gXnachmias_helpers',1, true,                               []; ...
    'gXnachmias_statelist',1,false,	arg_statelist}, ...
    cta{:}, varargin{:});