function mta_ = bias_task_args
% return the partial list of dXtask argumnets that is common to response
% modality tasks

feedbackSelect = { ...
    'showPctGood',      false; ...
    'showNumGood',      false; ...
    'showGoodRate',     false; ...
    'showPctCorrect',   true; ...
    'showNumCorrect',   false; ...
    'showCorrectRate',  false; ...
    'showTrialCount',   false; ...
    'showMoreFeedback', false};
feedbackSelect = cell2struct(feedbackSelect(:,2), feedbackSelect(:,1), 1);

mta_ = { ...
    'statesToFIRA', ...
    { ...
    'acquire',  1; ...
    'indicate', 3; ...
    'hold',     1; ...
    'settle',   1; ...
    'showStim', 3; ...
    'hideStim', 3; ...
    'respond',  3; ...
    'left',     1; ...
    'right',    1; ...
    'correct',  1; ...
    'incorrect',1; ...
    'error',    1}, ...
    ...
    'objectsToFIRA',    {'saveToFIRA'}, ...
    'anyStates',        {'correct', 'incorrect'}, ...
    'wrtState',         'showStim', ...
    'trialOrder',       'random', ...
    'feedbackSelect',   feedbackSelect, ...
    'showFeedback',     true, ...
    'timeout',          3600};