function index_ = taskRandomContinuous(varargin)
%Decide if the next in the sequence of numbers will be greater
%
%   index_ = taskRandomContinuous(varargin)
%
%   no eye tracker
%   gamepad or kbHID choices
%
%   varargin gets passed to dXtask/set via rAdd.
%
%   index_ specifies the new instance in ROOT_STRUCT.dXtask

% copyright 2007 Benjamin Heasly University of Pennsylvania
varargin
if nargin
    arg_helpers = {varargin{1}, varargin{2}, true}; % True refers to useASLt
    half        = varargin(3);
    varargin(1:3) = [];
else
    arg_helpers = {[]};
end

feedbackSelect = { ...
    'showPctGood',      false; ...
    'showNumGood',      false; ...
    'showGoodRate',     false; ...
    'showPctCorrect',   false; ...
    'showNumCorrect',   false; ...
    'showCorrectRate',  false; ...
    'showTrialCount',   false; ...
    'showMoreFeedback', true};
feedbackSelect = cell2struct(feedbackSelect(:,2), feedbackSelect(:,1), 1);

ptrs = { ...
    'estimate', 'dXtext', 2, 'string'; ...
    'start',    'dXtext', 4, 'string';...
    'flash', 'dXtext', 10, 'string'};
arg_dXtask = { ...
    'statesToFIRA', { ...
                    'waitMove',     3; ...
                    'waitLook',     1; ...
                    'lookStupid',   1; ...
                    'newNumber',    3; ...
                    'stayLook',     1; ...
                    'stayStupid',   1; ...
                    'inBox',        1; ...
                    'goTime',       1; ...
                    'newLine',      1; ...
                    'end',          1; ...
                    'sublim',       1; ...
                    'mask',         1; ...
                    'drawNew',      1}, ...
    'objectsToFIRA',    {'saveToFIRA'}, ...
    'ptrsToFIRA',       ptrs, ...
    'anyStates',        {'end'}, ...
    'noStates',         {'stayStupid'}, ...
    'wrtState',         'waitMove', ...
    'trialOrder',       'random', ...
    'timeout',          1e6, ...
    'feedbackSelect',   feedbackSelect, ...
    'moreFeedbackFunction', @errorFeedback, ...
    'showFeedback',     true, ...
    'userData',         0};

name = mfilename;
index_ = rAdd('dXtask', 1, {'root', false, true, false}, ...
    'name',	name(5:end), ...
    'blockReps', 1, ...
    'bgColor', [0,0,0], ...
    'helpers', { ...
    'gXpupil_text',                 1,  false,	[]; ...
    'gXrandomContinuous_helpers',	1,  false,	arg_helpers; ...
    'gXsublim_statelist',            1,  false,	half}, ...
    arg_dXtask{:}, varargin{:});