function dots_ = gXdots

% initial dXdots attributes
dtargs = { ...
    'x',            0, ...
    'y',            0, ...
    'diameter',     8, ...
    'size',         4, ...
    'speed',        8, ...
    'coherence',    0, ...
    'color',        [0,0,255], ...
    'direction',    0};

% initial target attributes
tgargs = { ...
    'x',            {0 -10 10}, ...
    'y',            {0 0 0},    ...
    'diameter',     {.4 .8 .8}, ...
    'diameter2',    {5 4 4}, ...
    'color',        [0,0,255]};

raargs = {'current', false, true, true};

dots_ = { ...
    'dXline',   1, raargs, {};     ...
	'dXdots',   1, raargs, dtargs; ...
    'dXtarget', 3, raargs, tgargs};