function modality_paradigm_sets
% a quick way to call some sets on dXparadigm, for all of the Nachmias
% tasks.

global ROOT_STRUCT

feedbackSelect = { ...
    'showPctGood',      false; ...
    'showNumGood',      false; ...
    'showGoodRate',     false; ...
    'showPctCorrect',   false; ...
    'showNumCorrect',   false; ...
    'showCorrectRate',  false; ...
    'showTrialCount',   false; ...
    'showMoreFeedback', true};
feedbackSelect = cell2struct(feedbackSelect(:,2), feedbackSelect(:,1), 1);

% set changes to paradigm
rSet('dXparadigm', 1, ...
    'saveToFIRA',           true, ...
    'FIRA_doWrite',         true, ...
    'iti',                  1, ...
    'moreFeedbackFunction', @randomFeedback, ...
    'showFeedback',         true, ...
    'feedbackSelect',       feedbackSelect);

% show the changes to paradigm
p = findobj('Tag', 'paradigmFigure');
if ~isempty(p)
    handles = guidata(p);
    dXparadigmGUI('bonusMagnus_Callback', handles.bonusMagnus, [], handles);
end

g = findobj('Name', 'dXgui');
if ~isempty(g)
    handles = guidata(g);
    dXGUI_sync(handles);
    drawnow
end