function arg_dXtask_ = cohTimeLearn_task_args
% return the partial list of dXtask argumnets that is common to all
% cohTimeLearn tasks

feedbackSelect = { ...
    'showPctGood',      false; ...
    'showNumGood',      false; ...
    'showGoodRate',     false; ...
    'showPctCorrect',   false; ...
    'showNumCorrect',   false; ...
    'showCorrectRate',  false; ...
    'showTrialCount',   false; ...
    'showMoreFeedback', false};
feedbackSelect = cell2struct(feedbackSelect(:,2), feedbackSelect(:,1), 1);

arg_dXtask_ = { ...
    'ptrsToFIRA', ...
    { ...
    'dotCoherence', 'dXdots', 1, 'coherence'; ...
    }, ...
    'statesToFIRA', ...
    { ...
    'clear',    3; ...
    'indicate', 3; ...
    'tone1',	1; ...
    'tone2',    1; ...
    'showStim', 3; ...
    'delay',    3; ...
    'respond',  3; ...
    'left',     1; ...
    'right',    1; ...
    'both',     1; ...
    'correct',  1; ...
    'incorrect',1; ...
    'error',    3; ...
    }, ...
    'wrtState',         'showStim', ...
    'objectsToFIRA',    {'saveToFIRA'}, ...
    'anyStates',        {'correct', 'incorrect'}, ...
    'bgColor',          [0,0,0], ...
    'trialOrder',       'random', ...
    'feedbackSelect',   feedbackSelect, ...
    'showFeedback',     true, ...
    'timeout',          3600};