function trials = RTDconfigureTrials(directions, coherences, directionPriors, ...
   trialsPerCoherence)
% function trials_ = RTDconfigureTrials(directions, coherences, directionPriors, ...
%   trialsPerCoherence)
%
% RTD = Response-Time Dots
%
% Create a list of trial structs for the given task. See below for the
%  struct fields, which are the primary data-storage bin for trial-by-trial
%  choice and timing information.
%
% Inputs:
%  directions           ... the dot directions to use
%  coherences           ... the coherences to use
%  directionPriors      ... to control prior probabilities of the two
%                             directions (nx2 vector)
%  trialsPerCoherence   ... total trials for each coherence
%
% 5/11/18 written by jig

if nargin < 1 || isempty(directions)
   directions = [0 180];
end

if nargin < 2 || isempty(coherences)
   coherences = nan;
end

if nargin < 3 || isempty(directionPriors)
   directionPriors = [1 1];
end

if nargin < 4 || isempty(trialsPerCoherence)
   trialsPerCoherence = 50;
end

% make array of directions
directionPriors = directionPriors./(sum(directionPriors));
directionArray = cat(1, ...
   repmat(directions(1), round(directionPriors(1).*trialsPerCoherence), 1), ...
   repmat(directions(2), round(directionPriors(2).*trialsPerCoherence), 1));

% make grid of directions, coherences
[directionGrid, coherenceGrid] = meshgrid(directionArray, coherences);

% get number of trials and make randomized vectors
numTrials = numel(directionGrid);
indices = randperm(numTrials);
directionGrid = directionGrid(indices)';
coherenceGrid = coherenceGrid(indices)';

% make structure array
trials = struct( ...
   'trialIndex', (1:numTrials)', ...
   'direction', num2cell(directionGrid), ...
   'coherence', num2cell(coherenceGrid), ...
   'choice', nan, ...
   'RT', nan, ...
   'correct', nan, ...
   'time_screen_roundTrip', 0, ...
   'time_local_trialStart', nan, ...
   'time_ui_trialStart', nan, ...
   'time_screen_trialStart', nan, ...
   'time_TTLBlock', nan, ...
   'time_TTLTrial', nan, ...
   'time_insOn', nan, ...
   'time_fixOn', nan, ...
   'time_targsOn', nan, ...
   'time_dotsOn', nan, ...
   'time_choice', nan, ...
   'time_dotsOff', nan, ...
   'time_fdbkOn', nan, ...
   'time_local_trialFinish', nan, ...
   'time_ui_trialFinish', nan, ...
   'time_screen_trialFinish', nan);
end

