function e_ = eq(t1, t2)%eq method for class dXtext: check for equivalent instances
%   e_ = eq(t1, t2)%
%   Some DotsX classes have eq methods which compare all the properties of
%   two instances to determine whether they are equivalent.
%
%   Returns boolean TRUE if instances are equivalent, FALSE if not.
%
%----------Special comments-----------------------------------------------
%-%%-% Overloaded eq method for class dXtext%----------Special comments-----------------------------------------------
%
%   See also eq dXtext
% written 8/28/03 by jigif length(t1.x) == length(t2.x) & ...	all(t1.x == t2.x) & ...	length(t1.y) == length(t2.y) & ...	all(t1.y == t2.y) & ...	length(t1.size) == length(t2.size) & ...	all(t1.size == t2.size) & ...	length(t1.bold) == length(t2.bold) & ...	all(t1.bold == t2.bold) & ...	length(t1.italic) == length(t2.italic) & ...	all(t1.italic == t2.italic) & ...	length(t1.underline) == length(t2.underline) & ...	all(t1.underline == t2.underline) & ...	length(t1.outline) == length(t2.outline) & ...	all(t1.outline == t2.outline) & ...	length(t1.color) == length(t2.color) & ...	all(t1.color == t2.color) & ...	t1.visible == t2.visible	    % ignoring font    	e_ = true;else	e_ = false;end