function index_ = taskRandomNumbers(varargin)
%Decide if the next in the sequence of numbers will be greater
%
%   index_ = taskRandomNumbers(varargin)
%
%   no eye tracker
%   lpHID or kbHID choices
%
%   varargin gets passed to dXtask/set via rAdd.
%
%   index_ specifies the new instance in ROOT_STRUCT.dXtask

% copyright 2007 Benjamin Heasly University of Pennsylvania

feedbackSelect = { ...
    'showPctGood',      false; ...
    'showNumGood',      false; ...
    'showGoodRate',     false; ...
    'showPctCorrect',   true; ...
    'showNumCorrect',   false; ...
    'showCorrectRate',  false; ...
    'showTrialCount',   false; ...
    'showMoreFeedback', false};
feedbackSelect = cell2struct(feedbackSelect(:,2), feedbackSelect(:,1), 1);

arg_dXtask = { ...
    'statesToFIRA', { ...
    'clear',    3; ...
    'showNum',  3; ...
    'left',     1; ...
    'right',    1; ...
    'correct',  1; ...
    'incorrect',1; ...
    'error',    3; ...
    'end',      3}, ...
    'objectsToFIRA',    {'saveToFIRA'}, ...
    'anyStates',        {'correct', 'incorrect'}, ...
    'wrtState',         'showNum', ...
    'trialOrder',       'random', ...
    'timeout',          100, ...
    'feedbackSelect',   feedbackSelect, ...
    'showFeedback',     true};

name = mfilename;
index_ = rAdd('dXtask', 1, {'root', false, true, false}, ...
    'name',	name(5:end), ...
    'blockReps', 1, ...
    'bgColor', [0,0,0], ...
    'helpers', { ...
    'gXrandom_text',        1,  true,   []; ...
    'gXrandom_helpers',     1,  true,   []; ...
    'gXrandom_statelist',   1,  false,	[]}, ...
    arg_dXtask{:}, varargin{:});