function text_ = gXrandom_text

% two text fields

arg_dXtext = { ...
    'string',   65, ...
    'x',        -2, ...
    'y',        1,  ...
    'size',     100, ...
    'font',     'Arial', ...
    'bold',     false, ...
    'italic',   false, ...
    'underline',false, ...
    'outline',  false, ...
    'color',    [255 255 0], ...
    'mode',     'TextFill', ...
    'visible',  true};

tony = {'current', false, true, false};
text_ = {'dXtext',  1,  tony,   arg_dXtext};